### ISSUE TITLE
> This should be available as a NuGet package ASAP!

### ISSUE THREAD

**Issue by chamik** [mariansam/Bogosort.NET#1]
What does ASAP mean? Anyway.. pls

**Comment by mariansam** [comment]
Okay, I guess I'm gonna do that rn. btw ASAP means _as soon as possibe_ 😐

**Comment by chamik** [comment]
That was a joke...

**Comment by mariansam** [comment]
I know.

Do I really have to make a Microsoft account for uploading a NuGet package...?

**Comment by chamik** [comment]
Yes, that's one of the reasons why I asked you to do it 🙃

**Comment by mariansam** [comment]
what

**Comment by mariansam** [comment]
Sorry for the delay, it's there - https://www.nuget.org/packages/Bogosort.NET

you can install by `dotnet add package Bogosort.NET --version 1.0.0`

enjoy!

**Comment by chamik** [comment]
Thank you very much, won't use it anyway 🙃
